version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '${postgres_port}:5432'
    environment:
      POSTGRESQL_USERNAME: ${postgres_username}
      POSTGRESQL_PASSWORD: ${postgres_password}
    volumes:
      - fintrack_pg_data:/bitnami/postgresql

volumes:
  fintrack_pg_data:
